// Auto-generated by scripts/generate_option_values.py; do not edit by hand.
export const OPTION_VALUES = {
  "regions": [
    "APAC",
    "EMEA"
  ],
  "bus": [
    "Core",
    "Growth",
    "Services"
  ],
  "product_lines": [
    "Alpha",
    "Beta",
    "Gamma",
    "ServicesPlus"
  ],
  "segments": [
    "Enterprise",
    "MidMarket",
    "SMB"
  ],
  "metrics": [
    "gross_margin",
    "opex",
    "revenue"
  ],
  "comparisons": [
    "plan",
    "prior",
    "all"
  ]
} as const;

export type ComparisonOption = typeof OPTION_VALUES.comparisons[number];
export type RegionOption = typeof OPTION_VALUES.regions[number];
export type BuOption = typeof OPTION_VALUES.bus[number];
export type ProductLineOption = typeof OPTION_VALUES.product_lines[number];
export type SegmentOption = typeof OPTION_VALUES.segments[number];
export type MetricOption = typeof OPTION_VALUES.metrics[number];
