"""
Generate distinct option values (regions, BUs, product lines, segments, metrics, comparisons)
from the source data and emit a TypeScript module consumed by the frontend.
"""

import json
from pathlib import Path
from typing import Dict, Iterable, Set

import sys

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.append(str(REPO_ROOT))

from src.config import PROJECT_ROOT
from src.tools.data_loader import DataRepository


COMPARISONS = ["plan", "prior", "all"]
TARGET_TS = PROJECT_ROOT / "frontend" / "src" / "optionValues.ts"


def unique_from_frames(frames: Iterable, column: str) -> Set[str]:
    values: Set[str] = set()
    for df in frames:
        if column not in df.columns:
            continue
        for raw in df[column].dropna().astype(str):
            val = raw.strip()
            if val:
                values.add(val)
    return values


def build_options() -> Dict[str, list]:
    repo = DataRepository()
    finance = repo.finance()
    orders = repo.orders()
    supply = repo.supply()
    shipments = repo.shipments()
    fx = repo.fx()
    events = repo.events()

    frames = [finance, orders, supply, shipments, fx, events]

    regions = unique_from_frames(frames, "region")
    bus = unique_from_frames(frames, "bu")
    product_lines = unique_from_frames(frames, "product_line")
    segments = unique_from_frames(frames, "segment")
    metrics = unique_from_frames([finance], "metric")

    return {
        "regions": sorted(regions),
        "bus": sorted(bus),
        "product_lines": sorted(product_lines),
        "segments": sorted(segments),
        "metrics": sorted(metrics),
        "comparisons": COMPARISONS,
    }


def emit_ts(options: Dict[str, list]) -> None:
    data_json = json.dumps(options, indent=2)
    content = (
        "// Auto-generated by scripts/generate_option_values.py; do not edit by hand.\n"
        "export const OPTION_VALUES = "
        f"{data_json} as const;\n\n"
        "export type ComparisonOption = typeof OPTION_VALUES.comparisons[number];\n"
        "export type RegionOption = typeof OPTION_VALUES.regions[number];\n"
        "export type BuOption = typeof OPTION_VALUES.bus[number];\n"
        "export type ProductLineOption = typeof OPTION_VALUES.product_lines[number];\n"
        "export type SegmentOption = typeof OPTION_VALUES.segments[number];\n"
        "export type MetricOption = typeof OPTION_VALUES.metrics[number];\n"
    )
    TARGET_TS.write_text(content)


def main() -> None:
    options = build_options()
    emit_ts(options)
    print(f"Wrote option values to {TARGET_TS}")


if __name__ == "__main__":
    main()
